language: rust
rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

branches:
  except:
    - test

matrix:
  allow_failures:
  - rust: beta
  - rust: nightly
  - os: osx

# needed, since travis doesn't build docs by default
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc

after_success:
  - >
    test $TRAVIS_PULL_REQUEST == "false"
    && test $TRAVIS_BRANCH == "master"
    && bash ./scripts/deploy-gh-pages.sh
